### ISSUE TITLE
RuntimeError: Ran out of search space (beam_cut_threshold too high)

### ISSUE THREAD

**Issue by lvxuan96** [nanoporetech/fast-ctc-decode#23]
My input is an 2D array（512×6）which looks like:
[[-6.14964533e+00 -4.50301647e+00 -1.26775427e+01 -1.32243423e+01
  -1.33028030e-02 -1.57202511e+01]
 [-6.09671593e-01 -9.38526917e+00 -1.16878452e+01 -1.45465679e+01
  -7.84433842e-01 -1.82103691e+01]
 [-2.47001648e-04 -1.24834585e+01 -1.32059736e+01 -1.49093075e+01
  -8.33115005e+00 -2.08991814e+01]
 ...
but I encountered a runtime error when I ran beam_search:
seq, _ = beam_search(probs_row, base_list, beam_size=3, beam_cut_threshold=0.1)
RuntimeError: Ran out of search space (beam_cut_threshold too high)
How to solve the problem?

**Comment by iiSeymour** [comment]
You are passing in log probabilities and the beam search expects probabilities so you will need to exponentiate them first.
