### ISSUE TITLE
blank symbol

### ISSUE THREAD

**Issue by AlexandrMoruk** [nanoporetech/fast-ctc-decode#25]
Hello!
Do I need to add a blank character to the alphabet for a real problem or should I manually remove blank characters later?

**Comment by AlexandrMoruk** [comment]
> Hello!
> Do I need to add a blank character to the alphabet for a real problem or should I manually remove blank characters later?

Excuse me, please. The first character is blank by default?

**Comment by iiSeymour** [comment]
Yes the first character/label is considered the blank label and decoder expects this. You don't have todo any manual removal of the blank.
