### ISSUE TITLE
Is there an easy way to get the probability of the best path?

### ISSUE THREAD

**Issue by fracav** [nanoporetech/fast-ctc-decode#28]
I'm working on an automatic handwriting transcription system, which uses ctc_decoding to get the final prediction. I was able to take advantage of your fantastic and lightning-fast implementation. I might find it useful to get the probability linked to the best path but I'm not very familiar with rust.

Thanks in advance

**Comment by iiSeymour** [comment]
Hey @fracav 

You do get a `path` returned from the search which you can use to index the probability matrix - maybe this solves your need?

**Comment by fracav** [comment]
Hi @iiSeymour 

Thank you very much for the reply, I followed your advice and I succeeded.
good evening :)
