### ISSUE TITLE
Install on jetson tx2

### ISSUE THREAD

**Issue by antoineTK** [nanoporetech/fast-ctc-decode#40]
Hi guys

I am installing openvino on nvidia jetson tx2 (arm64, ubuntu 18.04) and it is failing when trying to install fast-ctc-decode from pypi. 

Pip3 command fails (my python version is 3..6.9) saying no available versions are found. Same issue when trying to install a specific version.

I had a similar issue with rawpy and ended up installing it from source but I do not know how to install fast-ctc-decode from source.

Would someone be able to help?

Thank you!

**Comment by iiSeymour** [comment]
@antoineTK pypi doesn't host arm64 packages so you will have to build from source.

**Comment by antoineTK** [comment]
thank you @iiSeymour !

That's what I figured, would you be able to guide for building from source?

**Comment by iiSeymour** [comment]
It should just be a case of getting rust 1.54 installed then running `make build`.

**Comment by antoineTK** [comment]
it is building fine but `make test` fails saying `ModuleNotFoundError: No module named fast-ctc-decode`

and there is no rule for `make install` in Makefile, do I need to add variable to python path or something?

Thank you!

**Comment by antoineTK** [comment]
Thank you @iiSeymour that worked!
