### ISSUE TITLE
what's the difference between viterbi and beam search?

### ISSUE THREAD

**Issue by xiongjun19** [nanoporetech/fast-ctc-decode#46]
I found that the viterbi is really fast, but it's accuracy may a little lower than the beam search decoding. so I'm wondering what's the difference between viterbi and beam search ? is there any paper or reference ?

**Comment by iiSeymour** [comment]
Viterbi here is actually just a greedy decode _(take the highest probability at each time step i.e argmax)_.

- https://towardsdatascience.com/foundations-of-nlp-explained-visually-beam-search-how-it-works-1586b9849a24
- https://medium.com/@jessica_lopez/understanding-greedy-search-and-beam-search-98c1e3cd821d

**Comment by xiongjun19** [comment]
> Viterbi here is actually just a greedy decode _(take the highest probability at each time step i.e argmax)_.
> 
> * https://towardsdatascience.com/foundations-of-nlp-explained-visually-beam-search-how-it-works-1586b9849a24
> * https://medium.com/@jessica_lopez/understanding-greedy-search-and-beam-search-98c1e3cd821d

thanks, iiSeymour! that's really helpful !
