### ISSUE TITLE
Compilation error arm64

### ISSUE THREAD

**Issue by MdScntst** [nanoporetech/fast-ctc-decode#48]
Hello, I'm trying to build from source (v. 0.3.2), but gettng "The bindings crate pyo3 was not found in the dependencies list" after make build.
- Ubuntu 20.04
- rustc 1.62.1
- pyo3 0.16.5 
- maturin 0.13.1
- python 3.8

Cargo and pyproject are original from the git

**Comment by iiSeymour** [comment]
You need to specify the python feature - see https://github.com/nanoporetech/fast-ctc-decode/blob/master/Makefile
