### ISSUE TITLE
Publish arm64 OSX package on pypi

### ISSUE THREAD

**Issue by ilya-lavrenov** [nanoporetech/fast-ctc-decode#49]
Could you please package ARM64 OSX package?

**Comment by davnn** [comment]
Hey! We pretty much copied the fast-ctc-decode CI pipeline (nice work!) for [python-kmedoids](https://github.com/kno10/python-kmedoids) and recently added arm64 support. Have a look at <https://github.com/kno10/python-kmedoids/pull/18>, if you would like to publish a pull request yourself.

**Comment by davnn** [comment]
Ah sorry, I missed the OSX part, we already publish arm64 OSX wheels as well using Github Actions and it appears to be working well.

**Comment by ilya-lavrenov** [comment]
OSX packages are available only for Intel processors https://pypi.org/project/fast-ctc-decode/#files

**Comment by davnn** [comment]
Sorry I was talking about the <https://pypi.org/project/kmedoids/> package, which is using a very similar CI pipeline to build the wheels. I've added a pull request to add those features (arm64 OSX and linux support) to `fast-ctc-decode`.

**Comment by iiSeymour** [comment]
thanks @davnn - I've just published v0.3.5 to PyPi.
