### ISSUE TITLE
Can this work as a replacement for parlance/ctcdecode?

### ISSUE THREAD

**Issue by shamoons** [nanoporetech/fast-ctc-decode#8]
I'm having an impossible time installing the parlance one. My implementation has:
```
        try:
            from ctcdecode import CTCBeamDecoder
        except ImportError:
            raise ImportError("BeamCTCDecoder requires paddledecoder package.")
        self._decoder = CTCBeamDecoder(labels, lm_path, alpha, beta, cutoff_top_n, cutoff_prob, beam_width,
                                       num_processes, blank_index, log_probs_input=True)
```

But I'm wondering if I can drop this in instead?

**Comment by iiSeymour** [comment]
Yes, if you are not using an external language model then `fast-ctc-decode` can be used in place of the parlance beam search implementation. Ease of installation is a priority for this project.

**Comment by shamoons** [comment]
What do the various arguments map to?

**Comment by iiSeymour** [comment]
The first argument to the beam search is the probability output from your network where the first dimension is the width and the second is the number of features/labels *(WxC)*.

```python
>>> from fast_ctc_decode import beam_search
>>> posteriors = np.random.rand(100, 5).astype(np.float32)
>>>
>>> seq, path = beam_search(posteriors, alphabet="NACGT", beam_size=5)
```

Full documentation can be read either [here](https://github.com/nanoporetech/fast-ctc-decode/blob/master/src/lib.rs#L15) or by using `help(beam_search)` from the Python interpreter, also the [benchmark](https://github.com/nanoporetech/fast-ctc-decode/blob/master/tests/benchmark.py) script compares fast_ctc_decode against parlance. The key difference is parlance take a batch of network outputs *(NxWxC)*.
